### ISSUE TITLE
video loop error

### ISSUE THREAD

**Issue by fxck** [firebase/superstatic#204]
I'm getting this error 

```
Error: write EPIPE
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at WriteWrap.afterWrite (net.js:763:14)
Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)
Error: write EPIPE
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at WriteWrap.afterWrite (net.js:763:14)
Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)
```

with this piece of code 

```
        <video muted autoplay loop="loop">
            <source src="./videos/test.mp4" type="video/mp4" />
        </video>
```

after the first playback, any idea what could be causing it?

**Comment by bkendall** [comment]
This would need more information about what requests your browser is making. Because of that and the age of this issue, I'm going to close it.
